### PR TITLE
Adding `monitoring.googleapis.com` CRD

### PR DESCRIPTION
**Pull request by userbradley**
Adding the `monitoring.googleapis.com` CRD to the repo

## How have you tested this

```shell
kustomize build | kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/userbradley/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -verbose -output pretty
```

image

---

Commits are signed with my key and with `git commit -S`

### CODE REVIEW

**Comment by CyberHippo** [comment]
Hi @userbradley, we initiated (yet another) fork of this repo here : https://github.com/elmy-team/CRDs-catalog. Feel free to use it. We will migrate open PRs to our fork when we have time.

**Comment by userbradley** [comment]
@CyberHippo sounds good.

I'm happy to be a maintainer on your repo too as I've expressed interest on maintaining this repo 

Let me know, happy to have a chat

**Comment by CyberHippo** [comment]
@userbradley Sure, let know how you would like to maintain the repo (PR triage, etc.) per mail at hippolyte.vergnol[at]elmy.fr
We migrated a couple of open PRs to our repo

**Comment by userbradley** [comment]
@CyberHippo  I have sent you an email from my work account.

I'd look to be triage and approver for the repo. Let me know what you need from my side and we can get this working

**Comment by userbradley** [comment]
Closing this as it's picked up a bunch of guff

**Pull request closed without merging**
