### PR TITLE
Add clustersecret.io CRD

### PR DESCRIPTION
**Pull request by carl-reverb**
CRD Link: https://github.com/zakkg3/ClusterSecret/blob/master/charts/cluster-secret/crds/clustersecret-crd.yaml

The maintainer suggests either installing with Helm, which is the linked CRD, or by applying the `./yaml` directory from a cloned copy of their repo: https://github.com/zakkg3/ClusterSecret/blob/master/yaml/01_crd.yaml

### CODE REVIEW

**Comment by eyarz** [comment]
@carl-reverb because this is a new crd that you are adding to the catalog, please add a link to the crd in the relevant github project.
thanks :)

**Comment by carl-reverb** [comment]
Hi @eyarz , I don't understand exactly. Are you asking me to make a contribution to a different project in order to place a schema file in this project? Can you show me an example of what you're looking for, and what the purpose is?

**Comment by eyarz** [comment]
Sorry for the confusion 😅
I just need a link to the CRD on his GitHub project so I can validate that the naming pattern of the files is correct.
here is an example: https://github.com/datreeio/CRDs-catalog/pull/358

**Comment by carl-reverb** [comment]
Ok, thanks for the explanation, I updated the top comment here with the CRD information

**Review by eyarz — APPROVED** [review]

**Pull request merged**
