### PR TITLE
feat: fluent-operator CRDs (v3.2.0)

### PR DESCRIPTION
**Pull request by reegnz**
This PR aims to introduce [fluent-operator](https://github.com/fluent/fluent-operator) [fluent-bit CRDs](https://github.com/fluent/fluent-operator/tree/master/charts/fluent-operator/charts/fluent-bit-crds/crds) and [fluentd CRDs](https://github.com/fluent/fluent-operator/tree/master/charts/fluent-operator/charts/fluentd-crds/crds) from the latest version (v3.2.0) using the following script:

```sh
#!/usr/bin/env bash
# shellcheck disable=SC2064
set -euo pipefail

cleanup_cmd="rm -rf ${PWD}/fluent-operator ${PWD}/openapi2jsonschema.py"
trap "rm -f $cleanup_cmd" 0            # EXIT
trap "rm -f $cleanup_cmd; exit 1" 2    # INT
trap "rm -f $cleanup_cmd; exit 1" 1 15 # HUP TERM

FLUENT_OPERATOR_VERSION=v3.2.0
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
mkdir -p fluentbit.fluent.io
mkdir -p fluentd.fluent.io

mkdir fluent-operator
git clone --depth 1 --branch "${FLUENT_OPERATOR_VERSION}" https://github.com/fluent/fluent-operator.git fluent-operator
pushd fluent-operator
git checkout ${FLUENT_OPERATOR_VERSION}
popd

pushd fluentbit.fluent.io
for file in ../fluent-operator/charts/fluent-operator/charts/fluent-bit-crds/crds/*; do
  python3 ../openapi2jsonschema.py "${file}"
done
popd

pushd fluentd.fluent.io
for file in ../fluent-operator/charts/fluent-operator/charts/fluentd-crds/crds/*; do
  python3 ../openapi2jsonschema.py "${file}"
done
popd

```

### CODE REVIEW

**Comment by eyarz** [comment]
@reegnz please provide an info about the CRD origin with a link to the its repo ([example](https://github.com/datreeio/CRDs-catalog/pull/389))

**Comment by reegnz** [comment]
Will update, didn't have time to finish this yesterday. :)

**Comment by reegnz** [comment]
@eyarz  updated the PR with still missing CRD-s, and added a description to the PR.

**Comment by reegnz** [comment]
@eyarz I've repeated the import and provided a script in the description to make it reproducible.

**Review by eyarz — APPROVED** [review]

**Comment by eyarz** [comment]
LGTM

**Pull request merged**
