### PR TITLE
[pxc.percona.com] Add Percona XtraDB Cluster Operator Schemas

### PR DESCRIPTION
**Pull request by zhekazuev**
Added Percona XtraDB Cluster Operator Schemas.

Group: `pxc.percona.com`.

A list of CRDs:
- `PerconaXtraDBClusterBackup` - `v1`
- `PerconaXtraDBClusterRestore` - `v1`
- `PerconaXtraDBCluster` - `v1`

Here is the commands I used to generate them:

```bash
python openapi2jsonschema.py https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/main/deploy/bundle.yaml
```

Reference: <https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/main/deploy/bundle.yaml>
Source: <https://github.com/percona/percona-xtradb-cluster-operator>

### CODE REVIEW

**Comment by eyarz** [comment]
@zhekazuev, the `vx-x-x` apiVersion (**PerconaXtraDBCluster**) version convention is not according to the CRDs standard, so I'm not sure it will be parsed correctly.
Did you check this against your branch to verify it's working as expected?

**Comment by zhekazuev** [comment]
> @zhekazuev, the `vx-x-x` apiVersion (**PerconaXtraDBCluster**) version convention is not according to the CRDs standard, so I'm not sure it will be parsed correctly. Did you check this against your branch to verify it's working as expected?

Hi, yeah I know it is not looks correctly, but this is how it looks like in the CRDs, f.e.: https://github.com/percona/percona-xtradb-cluster-operator/blob/main/deploy/bundle.yaml#L482

P.S.

Ok I see that for all uncorrect versions:

> deprecationWarning: pxc.percona.com/v1-2-0 PerconaXtraDBCluster is deprecated and will be removed in v1.16.0; see v1.12.0 release notes for instructions to migrate to pxc.percona.com/v1

How do you think, should I delete these versions?

**Comment by eyarz** [comment]
the following schemas are pretty useless because they don't validate anything 😅
- v1-2-0
- v1-3-0
- v1-4-0
- v1-5-0
- v1-6-0
- v1-7-0
- v1-8-0
- v1-9-0
- v1-10-0
- v1-11-0

just delete them and we will be alright

**Comment by zhekazuev** [comment]
@eyarz 
Holy... 😅, Ok.

**Review by eyarz — APPROVED** [review]

**Pull request merged**
