### PR TITLE
[minio.min.io] Add MinIO CRDs

### PR DESCRIPTION
**Pull request by eaglesemanation**
Add MinIO CRDs

Group: minio.min.io

List of CRDs:

- `Tenant`
- `PolicyBinding`

Here are the commands that I used to generate them:
```
python openapi2jsonschema.py https://raw.githubusercontent.com/minio/operator/master/resources/base/crds/minio.min.io_tenants.yaml

python openapi2jsonschema.py https://raw.githubusercontent.com/minio/operator/master/resources/base/crds/sts.min.io_policybindings.yaml
```
Reference: [minio/operator/resources/base/crds@master](https://github.com/minio/operator/tree/d1dac6dd2b5857446a32c868207f758262104939/resources/base/crds)
Source: [minio/operator@master](https://github.com/minio/operator/tree/d1dac6dd2b5857446a32c868207f758262104939)

### CODE REVIEW

**Comment by eyarz** [comment]
@eaglesemanation the folder name should be [group]/[kind_apiVersion]
you need to replace `minio.min.io` with `sts.min.io`

**Review by eyarz — CHANGES_REQUESTED** [review]
check my comment

**Comment by eaglesemanation** [comment]
Sorry, completely forgot about this PR

**Comment by ElanHasson** [comment]
@eyarz can you merge this?

**Comment by ElanHasson** [comment]
@eaglesemanation I needed Minio schemas, so I have created this fork that we will be maintaining at https://github.com/InfinityFlowApp/CRDs-catalog. It'll be kept in sync with the `datreeio/CRDs-catalog` upstream.

Many thanks to the folks at @datreeio for starting this project! ❤️

**Comment by willejs** [comment]
I am after this too. Any chance of another review @eyarz ?

**Review by eyarz — APPROVED** [review]

**Pull request merged**
