### PR TITLE
HorizontalPodAutoscaler schemas

### PR DESCRIPTION
**Pull request by matjanos**
Schemas for HorizontalPodAutoscaler
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

### CODE REVIEW

**Comment by eyarz** [comment]
@matjanos HPA is not a CR, it's a native K8s object.
Therefore, it should be supported out of the box because it's already part of the [kubernetes-json-schema](https://github.com/yannh/kubernetes-json-schema) project.

which tool you're using for validating your HPA files? my guess is that you just need to configure it correctly to also use the HPA schemas :)

**Comment by matjanos** [comment]
hi @eyarz ,
Thanks! I'm using kubeconform and just found out that I can use another source to get native definitions:
https://github.com/yannh/kubeconform#openshift-schema-support

Closing this ticket!

**Comment by eyarz** [comment]
@matjanos the openshift schemas will not help in this case.
what you need to do is pass the right K8s version via the `-kubernetes-version` flag

**Comment by eyarz** [comment]
@matjanos the openshift schemas will not help in this case.
what you need to do is pass the right K8s version via the `-kubernetes-version` flag

**Pull request closed without merging**
