### PR TITLE
add linkerd crd

### PR DESCRIPTION
**Pull request by KyriosGN0**
Signed-off-by: AvivGuiser <aviv.guiser@placer.ai>

CRD source https://github.com/linkerd/linkerd2/tree/main/charts/linkerd-crds

### CODE REVIEW

**Comment by eyarz** [comment]
@KyriosGN0 please add a link to the CRD origin repo

**Comment by KyriosGN0** [comment]
@eyarz added

**Comment by KyriosGN0** [comment]
@eyarz im not sure, these were extracted with the CRD extractor util, the CRD spec that you referenced is only installed if a user sets some value to true in the crd chart, if you go to the templates folder there is a policy folder with the CRDs im adding in this PR

**Comment by eyarz** [comment]
[you're right](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-crds/templates/policy/httproute.yaml#L12).
I don't think it worth investigating why it's like that so I will just go ahead and merge it and if this doesn't work as expected, we will have a deeper look into it.

**Review by eyarz — APPROVED** [review]

**Pull request merged**
