### PR TITLE
chore(openebs): add `diskpool` v1beta2 CRD

### PR DESCRIPTION
**Pull request by marcolongol**

### CODE REVIEW

**Comment by userbradley** [comment]
Hi @marcolongol, thanks for submitting this PR!

Please can I ask you add to the description where you got this CRD from, so when we build out automation we can work on getting it to update automatically 

Any questions please ask!

**Comment by marcolongol** [comment]
Unfortunately the openebs team does not seem to provide the schemas directly, i had to pull the CRD from my cluster using `crd-extractor.sh` 

Here's the [source code](https://github.com/openebs/mayastor-control-plane/blob/864bf74589d12e0169e1cdb17f7784568f723258/k8s/operators/src/pool/diskpool/crd/v1beta2.rs) for the relevant CRD.

**Review by userbradley — APPROVED** [review]

**Comment by userbradley** [comment]
@eyarz I dont seem to have merge access 
image

**Comment by eyarz** [comment]
@userbradley I made some updates to your permissions. try now.

**Pull request merged**
