### PR TITLE
feat(*): Added Grafana and AWS CRDs

### PR DESCRIPTION
**Pull request by Moep90**

### CODE REVIEW

**Comment by eyarz** [comment]
@Moep90 can you please add a link to the crd origin on github?

**Comment by Moep90** [comment]
@eyarz sure! 
Their repository is building them using Kustomize I suppose, but here is the link to it https://github.com/grafana/grafana-operator/tree/master/config/crd

**Comment by Moep90** [comment]
@eyarz where do you want me to add the CRDs?
I did not found an example in the contribution guidelines as well as the latest PRs

However, the CRDs can be found here: https://github.com/grafana/grafana-operator/tree/master/config/crd

**Review by eyarz — APPROVED** [review]

**Comment by eyarz** [comment]
I just needed the link so we are set
you're right, there is no contribution guidelines and you are more then welcome to help with that 😅

**Pull request merged**
