### PR TITLE
Update Kyverno CRDs to current v1.12.4

### PR DESCRIPTION
**Pull request by tmyhu**
Used the CRD Extractor after a new, clean install of v1.12.4

### CODE REVIEW

**Comment by userbradley** [comment]
Thanks for submitting this PR, can you please add a link to your PR where you got the schema from (if public)

**Comment by tmyhu** [comment]
@userbradley updated the description

**Comment by tmyhu** [comment]
@userbradley @eyarz sorry to be a bother but any chance to get this merged soon? I'm stuck deploying kyverno as long as it's failing validation in our CI/CD pipeline ☹️

**Review by userbradley — APPROVED** [review]

**Comment by userbradley** [comment]
Haha no worries, we've all been there. That's why I became a maintainer!

**Pull request merged**
